FROM python:3.11-slim

WORKDIR /app
RUN pip install --no-cache-dir streamlit==1.41.1 pandas==2.2.3 plotly==5.24.1

COPY app.py ./app.py
COPY data ./data

EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
